/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.helpdesk.view;

import br.com.helpdesk.controller.DelegaUsuario;
import br.com.helpdesk.model.Cliente;
import br.com.helpdesk.model.Funcionario;
import br.com.helpdesk.model.usuario.Usuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author muril
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtUsuario = new javax.swing.JTextField();
        jtxtSenha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jbtEntrar = new javax.swing.JButton();
        jbtnSair = new javax.swing.JButton();
        lblUSUARIO = new javax.swing.JLabel();
        lblSENHA = new javax.swing.JLabel();
        FUNDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(jtxtUsuario);
        jtxtUsuario.setBounds(240, 160, 170, 30);

        jtxtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(jtxtSenha);
        jtxtSenha.setBounds(240, 210, 170, 30);

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HELP DESK - PIM 2018");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 10, 320, 40);

        jbtEntrar.setText("Entrar");
        jbtEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtEntrar);
        jbtEntrar.setBounds(240, 250, 70, 32);

        jbtnSair.setText("Cancelar");
        jbtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSairActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnSair);
        jbtnSair.setBounds(320, 250, 90, 32);

        lblUSUARIO.setForeground(new java.awt.Color(255, 255, 255));
        lblUSUARIO.setText("USUÁRIO ");
        getContentPane().add(lblUSUARIO);
        lblUSUARIO.setBounds(240, 140, 60, 20);

        lblSENHA.setForeground(new java.awt.Color(255, 255, 255));
        lblSENHA.setText("SENHA");
        getContentPane().add(lblSENHA);
        lblSENHA.setBounds(240, 190, 60, 20);

        FUNDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/helpdesk/view/img/wallpaper-1969945.jpg"))); // NOI18N
        getContentPane().add(FUNDO);
        FUNDO.setBounds(0, 0, 690, 460);

        setSize(new java.awt.Dimension(643, 461));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEntrarActionPerformed
        String usuario = jtxtUsuario.getText();
        String senha = jtxtSenha.getText();
        String acao = "logar";

        if (usuario.trim().isEmpty() || senha.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        } else {
            Usuario usu = new Usuario(usuario, senha);
            try {
                new DelegaUsuario().acoes(acao, usu, null, null);
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jbtEntrarActionPerformed

    private void jbtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSairActionPerformed
        jtxtUsuario.setText("");
        jtxtSenha.setText("");
    }//GEN-LAST:event_jbtnSairActionPerformed

    private void jtxtSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtSenhaKeyPressed

    }//GEN-LAST:event_jtxtSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FUNDO;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtEntrar;
    private javax.swing.JButton jbtnSair;
    private javax.swing.JPasswordField jtxtSenha;
    private javax.swing.JTextField jtxtUsuario;
    private javax.swing.JLabel lblSENHA;
    private javax.swing.JLabel lblUSUARIO;
    // End of variables declaration//GEN-END:variables
}
