/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.helpdesk.view;

import br.com.helpdesk.view.cadastro.*;
import br.com.helpdesk.view.chamado.*;
import br.com.helpdesk.view.relatorio.*;
import javax.swing.JFrame;

/**
 *
 * @author muril
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonChamadosAbertos = new javax.swing.JButton();
        jButtonRelatorios = new javax.swing.JButton();
        jButtonCadastrarUsuario = new javax.swing.JButton();
        jButtonSuporteAndamento = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButtonHistorico = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jButton6 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jMenuBarMenu = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuEquipamentos = new javax.swing.JMenu();
        jMenuItemEquipComputadores = new javax.swing.JMenuItem();
        jMenuImpressoras = new javax.swing.JMenu();
        jMenuItemNobreaks = new javax.swing.JMenuItem();
        jMenuEntidades = new javax.swing.JMenu();
        jMenuUsuarios = new javax.swing.JMenuItem();
        jMenuItemContatos = new javax.swing.JMenuItem();
        jMenuItemFornecedores = new javax.swing.JMenuItem();
        jMenuGestao = new javax.swing.JMenu();
        jMenuItemChamados = new javax.swing.JMenuItem();
        jMenuItemMissoes = new javax.swing.JMenuItem();
        jMenuManutencoes = new javax.swing.JMenu();
        jMenuSolicitacoes = new javax.swing.JMenu();
        jMenuItemSolicitacoesCompras = new javax.swing.JMenuItem();
        jMenuItemSolicitacoesManutencao = new javax.swing.JMenuItem();
        jMenuItemSolicitacoesEletrica = new javax.swing.JMenuItem();
        jMenuGarantias = new javax.swing.JMenu();
        jMenuItemComputadores = new javax.swing.JMenuItem();
        jMenuInformacoes = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu19 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HELP DESK");
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(null);

        jButtonChamadosAbertos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonChamadosAbertos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/helpdesk/view/img/technical_wrench.png"))); // NOI18N
        jButtonChamadosAbertos.setText("CHAMADOS ABERTOS");
        jButtonChamadosAbertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChamadosAbertosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonChamadosAbertos);
        jButtonChamadosAbertos.setBounds(160, 10, 337, 150);

        jButtonRelatorios.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/helpdesk/view/img/copy2.png"))); // NOI18N
        jButtonRelatorios.setText("        RELATÓRIOS       ");
        jButtonRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatoriosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRelatorios);
        jButtonRelatorios.setBounds(160, 180, 340, 160);

        jButtonCadastrarUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonCadastrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/helpdesk/view/img/group.png"))); // NOI18N
        jButtonCadastrarUsuario.setText("CADASTRAR USUÁRIO");
        jButtonCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrarUsuario);
        jButtonCadastrarUsuario.setBounds(510, 10, 330, 150);

        jButtonSuporteAndamento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonSuporteAndamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/helpdesk/view/img/hourglass.png"))); // NOI18N
        jButtonSuporteAndamento.setText("SUPORTE EM ANDAMENTO");
        jButtonSuporteAndamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuporteAndamentoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSuporteAndamento);
        jButtonSuporteAndamento.setBounds(510, 180, 330, 160);

        jButton5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButton5.setText("COMPRAS");
        jButton5.setMaximumSize(new java.awt.Dimension(70, 23));
        jButton5.setMinimumSize(new java.awt.Dimension(70, 23));
        getContentPane().add(jButton5);
        jButton5.setBounds(10, 80, 140, 60);

        jButtonHistorico.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jButtonHistorico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/helpdesk/view/img/1.png"))); // NOI18N
        jButtonHistorico.setText("HISTORICO");
        getContentPane().add(jButtonHistorico);
        jButtonHistorico.setBounds(10, 10, 140, 60);

        jButton7.setText("jButton7");
        getContentPane().add(jButton7);
        jButton7.setBounds(10, 150, 140, 60);

        jButton8.setText("jButton5");
        getContentPane().add(jButton8);
        jButton8.setBounds(10, 430, 140, 60);

        jButton9.setText("jButton5");
        getContentPane().add(jButton9);
        jButton9.setBounds(10, 360, 140, 60);

        jButton1.setText("jButton1");
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 350, 340, 160);

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/helpdesk/view/img/windows.png"))); // NOI18N
        jButton2.setText("BASE DE CONHECIMENTOS");
        getContentPane().add(jButton2);
        jButton2.setBounds(860, 180, 340, 160);

        jButton4.setText("jButton4");
        getContentPane().add(jButton4);
        jButton4.setBounds(10, 290, 140, 60);

        jButton10.setText("jButton10");
        getContentPane().add(jButton10);
        jButton10.setBounds(10, 220, 140, 60);
        getContentPane().add(jCalendar1);
        jCalendar1.setBounds(860, 10, 340, 160);

        jButton6.setText("jButton6");
        getContentPane().add(jButton6);
        jButton6.setBounds(510, 350, 340, 160);

        jButton13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/helpdesk/view/img/envelope_open.png"))); // NOI18N
        jButton13.setText("               CHAT             ");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(860, 350, 340, 160);

        jMenuCadastro.setText("Cadastros");

        jMenuEquipamentos.setText("Equipamentos");

        jMenuItemEquipComputadores.setText("Computadores");
        jMenuEquipamentos.add(jMenuItemEquipComputadores);

        jMenuImpressoras.setText("Impressoras");
        jMenuEquipamentos.add(jMenuImpressoras);

        jMenuItemNobreaks.setText("NoBreaks");
        jMenuEquipamentos.add(jMenuItemNobreaks);

        jMenuCadastro.add(jMenuEquipamentos);

        jMenuEntidades.setText("Entidades");

        jMenuUsuarios.setText("Usuários");
        jMenuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuariosActionPerformed(evt);
            }
        });
        jMenuEntidades.add(jMenuUsuarios);

        jMenuItemContatos.setText("Contatos");
        jMenuEntidades.add(jMenuItemContatos);

        jMenuItemFornecedores.setText("Fornecedores");
        jMenuItemFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFornecedoresActionPerformed(evt);
            }
        });
        jMenuEntidades.add(jMenuItemFornecedores);

        jMenuCadastro.add(jMenuEntidades);

        jMenuBarMenu.add(jMenuCadastro);

        jMenuGestao.setText("Gestão");

        jMenuItemChamados.setText("Chamados");
        jMenuItemChamados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemChamadosActionPerformed(evt);
            }
        });
        jMenuGestao.add(jMenuItemChamados);

        jMenuItemMissoes.setText("Missões");
        jMenuGestao.add(jMenuItemMissoes);

        jMenuManutencoes.setText("Manutenções");
        jMenuGestao.add(jMenuManutencoes);

        jMenuSolicitacoes.setText("Solicitações");

        jMenuItemSolicitacoesCompras.setText("Compras");
        jMenuSolicitacoes.add(jMenuItemSolicitacoesCompras);

        jMenuItemSolicitacoesManutencao.setText("Manutenção");
        jMenuSolicitacoes.add(jMenuItemSolicitacoesManutencao);

        jMenuItemSolicitacoesEletrica.setText("Eletrica");
        jMenuSolicitacoes.add(jMenuItemSolicitacoesEletrica);

        jMenuGestao.add(jMenuSolicitacoes);

        jMenuGarantias.setText("Garantias");

        jMenuItemComputadores.setText("Computadores");
        jMenuGarantias.add(jMenuItemComputadores);

        jMenuGestao.add(jMenuGarantias);

        jMenuBarMenu.add(jMenuGestao);

        jMenuInformacoes.setText("Informações ");

        jMenu12.setText("Gráficos");

        jMenuItem10.setText("Fat. Impressão");
        jMenu12.add(jMenuItem10);

        jMenuItem11.setText("Computadores");
        jMenu12.add(jMenuItem11);

        jMenuInformacoes.add(jMenu12);

        jMenu13.setText("Relatórios");

        jMenu15.setText("Computadores");

        jMenu18.setText("Inventários");

        jMenuItem12.setText("Computadores");
        jMenu18.add(jMenuItem12);

        jMenuItem13.setText("Comp. por Estado");
        jMenu18.add(jMenuItem13);

        jMenu15.add(jMenu18);

        jMenu19.setText("Garantias");
        jMenu15.add(jMenu19);

        jMenu13.add(jMenu15);

        jMenu16.setText("Impressoras");

        jMenuItem14.setText("Fat. Impressões");
        jMenu16.add(jMenuItem14);

        jMenuItem15.setText("Lista Impressoras");
        jMenu16.add(jMenuItem15);

        jMenu13.add(jMenu16);

        jMenu17.setText("Compras");

        jMenuItem16.setText("Compras Concluídas");
        jMenu17.add(jMenuItem16);

        jMenuItem17.setText("Compras Pendentes");
        jMenu17.add(jMenuItem17);

        jMenuItem18.setText("Compras Canceladas");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu17.add(jMenuItem18);

        jMenu13.add(jMenu17);

        jMenuInformacoes.add(jMenu13);

        jMenu14.setText("Ajuda");
        jMenuInformacoes.add(jMenu14);

        jMenuBarMenu.add(jMenuInformacoes);

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuBarMenu.add(jMenuSair);

        setJMenuBar(jMenuBarMenu);

        setSize(new java.awt.Dimension(1250, 820));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFornecedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemFornecedoresActionPerformed

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed

        System.exit(0);

    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jButtonCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarUsuarioActionPerformed

        JFrame Usuario = new Usuario();
        Usuario.setVisible(true);

    }//GEN-LAST:event_jButtonCadastrarUsuarioActionPerformed

    private void jMenuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuariosActionPerformed

        JFrame Usuario = new Usuario();
        Usuario.setVisible(true);

    }//GEN-LAST:event_jMenuUsuariosActionPerformed

    private void jButtonChamadosAbertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChamadosAbertosActionPerformed

        JFrame ChamadoAberto;
        ChamadoAberto = new ChamadoAberto();
        ChamadoAberto.setVisible(true);

    }//GEN-LAST:event_jButtonChamadosAbertosActionPerformed

    private void jButtonRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatoriosActionPerformed

        JFrame RelatorioChamado = new RelatorioChamado();
        RelatorioChamado.setVisible(true);

    }//GEN-LAST:event_jButtonRelatoriosActionPerformed

    private void jMenuItemChamadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemChamadosActionPerformed

        JFrame ChamadoAberto = new ChamadoAberto();
        ChamadoAberto.setVisible(true);

    }//GEN-LAST:event_jMenuItemChamadosActionPerformed

    private void jButtonSuporteAndamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuporteAndamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSuporteAndamentoActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

        JFrame RelatorioHistorico = new RelatorioHistorico();
        RelatorioHistorico.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonCadastrarUsuario;
    private javax.swing.JButton jButtonChamadosAbertos;
    private javax.swing.JButton jButtonHistorico;
    private javax.swing.JButton jButtonRelatorios;
    private javax.swing.JButton jButtonSuporteAndamento;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenuBar jMenuBarMenu;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuEntidades;
    private javax.swing.JMenu jMenuEquipamentos;
    private javax.swing.JMenu jMenuGarantias;
    private javax.swing.JMenu jMenuGestao;
    private javax.swing.JMenu jMenuImpressoras;
    private javax.swing.JMenu jMenuInformacoes;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItemChamados;
    private javax.swing.JMenuItem jMenuItemComputadores;
    private javax.swing.JMenuItem jMenuItemContatos;
    private javax.swing.JMenuItem jMenuItemEquipComputadores;
    private javax.swing.JMenuItem jMenuItemFornecedores;
    private javax.swing.JMenuItem jMenuItemMissoes;
    private javax.swing.JMenuItem jMenuItemNobreaks;
    private javax.swing.JMenuItem jMenuItemSolicitacoesCompras;
    private javax.swing.JMenuItem jMenuItemSolicitacoesEletrica;
    private javax.swing.JMenuItem jMenuItemSolicitacoesManutencao;
    private javax.swing.JMenu jMenuManutencoes;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuSolicitacoes;
    private javax.swing.JMenuItem jMenuUsuarios;
    // End of variables declaration//GEN-END:variables
}
