/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.helpdesk.view;

import br.com.helpdesk.model.Chamado;
import br.com.helpdesk.session.Sessao;
import br.com.helpdesk.view.cadastro.*;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author muril
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Menu(boolean permissao) {
        initComponents();
        
        verificaPermissao(permissao);
    }
    
    public void verificaPermissao(boolean permissao) {
        jbtnUsuario.setVisible(permissao);
        jbtnFuncionario.setVisible(permissao);
        jbtnCliente.setVisible(permissao);
        jbtnChamado.setVisible(permissao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnChamado = new javax.swing.JButton();
        jbtnFuncionario = new javax.swing.JButton();
        jbtnUsuario = new javax.swing.JButton();
        jbtnCliente = new javax.swing.JButton();
        jMenuBarMenu = new javax.swing.JMenuBar();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HELP DESK");
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(null);

        jbtnChamado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbtnChamado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/helpdesk/view/img/technical_wrench.png"))); // NOI18N
        jbtnChamado.setText("CHAMADOS");
        jbtnChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChamadoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnChamado);
        jbtnChamado.setBounds(10, 20, 330, 150);

        jbtnFuncionario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbtnFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/helpdesk/view/img/copy2.png"))); // NOI18N
        jbtnFuncionario.setText("FUNCIONÁRIOS");
        jbtnFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFuncionarioActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnFuncionario);
        jbtnFuncionario.setBounds(410, 20, 340, 160);

        jbtnUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbtnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/helpdesk/view/img/group.png"))); // NOI18N
        jbtnUsuario.setText("USUÁRIOS");
        jbtnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnUsuario);
        jbtnUsuario.setBounds(410, 200, 340, 160);

        jbtnCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbtnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/helpdesk/view/img/copy2.png"))); // NOI18N
        jbtnCliente.setText("CLIENTES");
        jbtnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCliente);
        jbtnCliente.setBounds(20, 200, 340, 160);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuBarMenu.add(jMenuSair);

        setJMenuBar(jMenuBarMenu);

        setSize(new java.awt.Dimension(789, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente sair do sistema?");
        if (resposta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jbtnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUsuarioActionPerformed
        try {
            JFrame UsuarioView = null;
            try {
                UsuarioView = new UsuarioView();
            } catch (ParseException ex) {
                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
            }
            UsuarioView.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnUsuarioActionPerformed

    private void jbtnChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChamadoActionPerformed
        JFrame chaView = null;
        try {
            chaView = new ChamadoView();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        chaView.setVisible(true);
        

    }//GEN-LAST:event_jbtnChamadoActionPerformed

    private void jbtnFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFuncionarioActionPerformed
        
        JFrame funView = null;
        try {
            funView = new FuncionarioView();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        funView.setVisible(true);

    }//GEN-LAST:event_jbtnFuncionarioActionPerformed

    private void jbtnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClienteActionPerformed
        JFrame cliView = null;
        try {
            cliView = new ClienteView();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        cliView.setVisible(true);
    }//GEN-LAST:event_jbtnClienteActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente sair do sistema?");
        if (resposta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuSairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu(true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBarMenu;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JButton jbtnChamado;
    private javax.swing.JButton jbtnCliente;
    private javax.swing.JButton jbtnFuncionario;
    private javax.swing.JButton jbtnUsuario;
    // End of variables declaration//GEN-END:variables
}
